apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  labels:
    ignite-cluster: core
    app: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
  replicas: {{ .Values.OpenNMS.MinionGateway.Replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
        ignite-cluster: core
    spec:
      serviceAccountName: {{ .Values.OpenNMS.Minion.ServiceName }}-sa
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      containers:
        - name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
          image: {{ .Values.OpenNMS.MinionGateway.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.Minion.ImagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"  # FIXME: Permanent debug port, enable only for dev mode
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.Kafka.ServiceName }}:{{ .Values.Kafka.Port }}"
            - name: IGNITE_UPDATE_NOTIFIER # Disable Ignite version lookups
              value: "false"
          ports:
            - name: http
              containerPort: {{ .Values.OpenNMS.MinionGateway.Port }}
            - name: grpc
              containerPort: {{ .Values.OpenNMS.MinionGateway.GrpcPort }}
            - name: internal-grpc
              containerPort: {{ .Values.OpenNMS.MinionGateway.InternalGrpcPort }}
            - name: ig-client
              containerPort: {{ .Values.OpenNMS.MinionGateway.IgniteClientPort }}
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.MinionGateway.Resources.Limits.Cpu }}"
              memory: "{{ .Values.OpenNMS.MinionGateway.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.MinionGateway.Resources.Requests.Cpu }}"
              memory: "{{ .Values.OpenNMS.MinionGateway.Resources.Requests.Memory }}"
