apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.OpenNMS.Minion.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.Minion.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.OpenNMS.Minion.SshPort }}
      protocol: TCP
      name: ssh
    - port: {{ .Values.OpenNMS.Minion.Port }}
      protocol: TCP
      name: http
  selector:
    run: {{ .Values.OpenNMS.Minion.ServiceName }}
