Namespace: tilt-instance
Host: onmshs.local
HostIp: 127.0.0.1
Port: 1443
Protocol: https
TLS:
  Enabled: True
  CertificateGeneration: false
  Cert:
    Name: opennms-ui-certificate
Keycloak:
  AdminPassword: admin
  HostnamePort: 1443
  HostnameAdminUrl: https://onmshs.local:1443/auth

Ingress:
  Enabled: false

OpenNMS:
  global:
    openTelemetry:
      otlpTracesEndpoint: "http://jaeger-collector:4317"

  API:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  UI:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
    IngressAnnotations: {}
  Minion:
    addTestLocation: true
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  MinionGateway:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
    env:
      OTEL_JAVAAGENT_ENABLED: "true" # Enable for local development since it adds useful data
    IngressAnnotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        # This adds the tenant-id and location to the response headers sent to the client so we can use them in
        # logging. This is bit circuitous, and it is unnecessary to send these to the client, but this was a way I
        # could figure out how to get the tenant and minion information in the logs using $sent_http_x_tenant_id
        # and $sent_http_x_location once these response headers are added. They also seem to need to be in the
        # location block to work.
        # Note: The response headers are prefixed with "x-", although the headers from the auth service are not.
        # Note: I am being a little naughty and depending an internal implementation detail of ingress-nginx by
        # using the authHeader* variables. These are created by ingress-nginx from the auth-response-headers
        # annotation. The naming of the authHeader* variables is sensitive to the order of the headers in the
        # nginx.ingress.kubernetes.io/auth-response-headers annotation.
        add_header x-tenant-id "$authHeader0" always;
        add_header x-location "$authHeader1" always;
        set $dummy_val "$opentelemetry_context_traceparent"; # workaround for https://github.com/kubernetes/ingress-nginx/issues/9811
        grpc_set_header 'traceparent' $opentelemetry_context_traceparent; # This doesn't get sent downstream normally. :(
  MinionCertificateManager:
    Enabled: true
    CaSecretName: root-ca-certificate
    MtlsSecretName: client-root-ca-certificate
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  MinionCertificateVerifier:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  Inventory:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  Notification:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  Events:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  DataChoices:
    Resources:
      Limits:
        Cpu: '0'
        Memory: '0'
      Requests:
        Cpu: '0'
        Memory: '0'
  Core:
    Resources:
      Limits:
        Cpu: '0'
        Memory: 4Gi
      Requests:
        Cpu: '0'
        Memory: 2Gi
Grafana:
  Resources:
    Limits:
      Cpu: 500m
      Memory: 1Gi
    Requests:
      Cpu: 100m
      Memory: 100Mi
Prometheus:
  Server:
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
  PushGateway:
    Resources:
      Limits:
        Cpu: "1"
        Memory: 512Mi
      Requests:
        Cpu: 100m
        Memory: 100Mi
Kafka:
  LocalPort: 24092
