# Use local, in-memory storage.
# We set a limit on number of traces to store with a command-line arg later.
provisionDataStore:
  cassandra: false
storage:
  type: none

# Disable individual services
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false

# Use the all-in-one service
allInOne:
  enabled: true
  args:
    - --memory.max-traces=10000
