apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-env
  namespace: {{ .Release.Namespace }}
data:
{{- if .Values.OpenNMS.global.enableJsonLogging }}
  SPRING_PROFILES_INCLUDE: json-logging
{{- end }}
{{- with .Values.OpenNMS.global.springBoot }}
  {{- range $key, $val := .env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
{{- if .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint }}
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: {{ .Values.OpenNMS.global.openTelemetry.otlpTracesEndpoint | toYaml }}
{{- else }}
  OTEL_TRACES_EXPORTER: "none"
{{- end }}
  OTEL_METRICS_EXPORTER: "none"
{{- with .Values.OpenNMS.global.openTelemetry }}
  {{- range $key, $val := .env }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
