apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Prometheus.Server.ServiceName }}
  labels:
    app: {{ .Values.Prometheus.Server.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.Prometheus.Server.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.Prometheus.Server.ServiceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.Prometheus.Server.ServiceName }}
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "{{ .Values.NodeRestrictions.Key }}"
                    operator: In
                    values:
                      - {{ .Values.NodeRestrictions.Value }}
      {{- end }}
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config-map
      containers:
        - name: {{ .Values.Prometheus.Server.ServiceName }}
          image: {{ .Values.Prometheus.Server.Image }}
          ports:
            - containerPort: {{ .Values.Prometheus.Server.Port }}
          resources:
            limits:
              cpu: {{ .Values.Prometheus.Server.Resources.Limits.Cpu }}
              memory: {{ .Values.Prometheus.Server.Resources.Limits.Memory }}
            requests:
              cpu: {{ .Values.Prometheus.Server.Resources.Requests.Cpu }}
              memory: {{ .Values.Prometheus.Server.Resources.Requests.Memory }}
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: "/etc/prometheus/prometheus.yml"
              subPath: "prometheus.yml"
