version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@0.0.2

workflows:
  version: 2

  setup:
    jobs:
      - path-filtering/filter:
          mapping: |
            .circleci/.* run-job-no-ops true
            LICENSE.md run-job-no-ops true
            README.md run-job-no-ops true
            design/.* run-job-no-ops true
            howto/.* run-job-no-ops true
            local-docker-compose/.* run-job-no-ops true
            platform/.* run-job-no-ops true
            rest-server/.* run-job-no-ops true
            skaffold.yaml/.* run-job-no-ops true
            tools/.* run-job-no-ops true
            ui/.* run-job-no-ops true
            dev/.* run-job-dev true
            external-it/.* run-job-external-it true
          
          base-revision: << pipeline.git.branch >>
          config-path: .circleci/workflows.yml
