apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.Core.ServiceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
    app.kubernetes.io/name: {{ .Values.OpenNMS.Core.ServiceName }}
    ignite-cluster: core
  annotations:
    autoupdate: "true"
spec:
  replicas: {{ .Values.OpenNMS.Core.Replicas }}
  selector:
    matchLabels:
      app: {{ .Values.OpenNMS.Core.ServiceName }}
      ignite-cluster: core
  template:
    metadata:
      labels:
        app: {{ .Values.OpenNMS.Core.ServiceName }}
        ignite-cluster: core
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      tolerations:
        - effect: "NoSchedule"
          key: "{{ .Values.NodeRestrictions.Key }}"
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: "{{ .Values.NodeRestrictions.Key }}"
                operator: In
                values:
                - {{ .Values.NodeRestrictions.Value }}
      {{- end }}
      terminationGracePeriodSeconds: 120
      containers:
        - name: {{ .Values.OpenNMS.Core.ServiceName }}
          image: {{ .Values.OpenNMS.Core.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.Core.ImagePullPolicy }}
          args: [ "-f" ]
          env:
            - name: JAVA_TOOL_OPTIONS
              #value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"
            - name: EXTRA_JAVA_OPTS
              value: "-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true"
            - name: PGSQL_SERVICE_NAME
              value: {{ .Values.Postgres.ServiceName }}
            - name: PGSQL_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: adminUser
            - name: PGSQL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: adminPwd
            - name: PGSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: opennmsUser
            - name: PGSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: opennmsPwd
            - name: KAFKA_BROKER_HOST
              value: "{{ .Values.Kafka.ServiceName }}"
            - name: KAFKA_BROKER_PORT
              value: "{{ .Values.Kafka.Port }}"
            - name: NOTIFICATION_KAFKA_TOPIC
              value: "org.opennms.horizon.notifications.alarms"
            - name: ACTIVEMQ_BROKER_URL
              value: "tcp://localhost:61616"
            - name: KEYCLOAK_BASE_URL
              value: "http://{{ .Values.Keycloak.ServiceName }}:{{ .Values.Keycloak.Port }}{{ .Values.Keycloak.Path }}/"
            - name: KEYCLOAK_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.Keycloak.ServiceName }}-initial-admin
                  key: password
            - name: PROMETHEUS_PUSHGATEWAY_URL
              value: "http://{{ .Values.Prometheus.PushGateway.ServiceName }}:{{ .Values.Prometheus.PushGateway.Port }}"
          volumeMounts:
            - name: config-volume
              mountPath: "/opt/horizon-stream/etc/org.opennms.horizon.alarmd.camel.cfg"
              subPath: "useKafka"
            - name: config-volume
              mountPath: "/opt/horizon-stream/etc/org.opennms.horizon.eventd.camel.cfg"
              subPath: "useKafka"
            - name: config-volume
              mountPath: "/opt/horizon-stream/etc/users.properties"
              subPath: "karafUsers"
              readOnly: true
          ports:
            - name: ssh
              containerPort: {{ .Values.OpenNMS.Core.SshPort }}
            - name: http
              containerPort: {{ .Values.OpenNMS.Core.HttpPort }}
            - name: grpc
              containerPort: {{ .Values.OpenNMS.Core.GrpcPort }}                        
            - name: ignite1
              containerPort: 47100
            - name: ignite2
              containerPort: 47500
          {{- if not .Values.TestDeploy }}
{{/*    TODO  livenessProbe:*/}}
{{/*          readinessProbe:*/}}
{{/*          startupProbe:*/}}
          {{- end }}
          resources:
            limits:
              cpu: "{{ .Values.OpenNMS.Core.Resources.Limits.Cpu }}"
              memory: "{{ .Values.OpenNMS.Core.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.OpenNMS.Core.Resources.Requests.Cpu }}"
              memory: "{{ .Values.OpenNMS.Core.Resources.Requests.Memory }}"
      volumes:
        - name: config-volume
          configMap:
            name: opennms-config
