apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
  name: {{ .Values.OpenNMS.Core.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.OpenNMS.Core.SshPort }}
      protocol: TCP
      name: ssh
    - port: {{ .Values.OpenNMS.Core.HttpPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.OpenNMS.Core.GrpcPort }}
      protocol: TCP
      name: grpc
  selector:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
  type: NodePort
