kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.OpenNMS.Core.ServiceName }}-rb
  labels:
    app: {{ .Values.OpenNMS.Core.ServiceName }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.OpenNMS.Core.ServiceName }}-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: role-endpoints
  apiGroup: rbac.authorization.k8s.io
