Host: onmshs
OpenNMS:
  API:
    Image: opennms/horizon-stream-rest-server:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MetricsProcessor:
    Image: opennms/horizon-stream-metrics-processor:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  UI:
    Image: opennms/horizon-stream-ui:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Minion:
    Image: opennms/horizon-stream-minion:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MinionGateway:
    Image: opennms/horizon-stream-minion-gateway:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MinionGatewayGrpcProxy:
    Enabled: true
    Image: opennms/horizon-stream-minion-gateway-grpc-proxy:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Inventory:
    Image: opennms/horizon-stream-inventory:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Alarm:
    Image: opennms/horizon-stream-alarm:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Notification: 
    Image: opennms/horizon-stream-notification:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Events:
    Image: opennms/horizon-stream-events:latest
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
Keycloak:
  Image: opennms/horizon-stream-keycloak:latest
  AdminUsername: admin
  AdminPassword: admin
Grafana:
  Enabled: true
  Image: opennms/horizon-stream-grafana:latest
Ingress:
  Enabled: true

