Host: onmshs
OpenNMS:
  Core:
    Image: opennms/horizon-stream-core:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  API:
    Image: opennms/horizon-stream-rest-server:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MetricsProcessor:
    Image: opennms/horizon-stream-metrics-processor:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  UI:
    Image: opennms/horizon-stream-ui:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Minion:
    Image: opennms/horizon-stream-minion:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MinionGateway:
    Image: opennms/horizon-stream-minion-gateway:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MinionGatewayGrpcProxy:
    Image: opennms/horizon-stream-minion-gateway-grpc-proxy:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Inventory:
    Image: opennms/horizon-stream-inventory:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Alarm:
    Image: opennms/horizon-stream-alarm:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Notification: 
    Image: opennms/horizon-stream-notification:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Events:
    Image: opennms/horizon-stream-events:local
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
Keycloak:
  Image: opennms/horizon-stream-keycloak:local
  AdminUsername: admin
  AdminPassword: admin
Grafana:
  Image: opennms/horizon-stream-grafana:local
