Host: onmshs
OpenNMS:
  API:
    Image: opennms/horizon-stream-rest-server:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MetricsProcessor:
    Image: opennms/horizon-stream-metrics-processor:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  UI:
    Image: opennms/horizon-stream-ui:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Minion:
    Image: opennms/horizon-stream-minion:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MinionGateway:
    Image: opennms/horizon-stream-minion-gateway:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  MinionGatewayGrpcProxy:
    Enabled: true
    Image: opennms/horizon-stream-minion-gateway-grpc-proxy:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Inventory:
    Image: opennms/horizon-stream-inventory:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Alarm:
    Image: opennms/horizon-stream-alarm:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Notification: 
    Image: opennms/horizon-stream-notification:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
  Events:
    Image: opennms/horizon-stream-events:v0.0.32-dev
    Resources:
      Limits:
        Cpu: "0"
        Memory: "0"
      Requests:
        Cpu: "0"
        Memory: "0"
Keycloak:
  Image: opennms/horizon-stream-keycloak:v0.0.32-dev
  AdminUsername: admin
  AdminPassword: admin
Grafana:
  Enabled: true
  Image: opennms/horizon-stream-grafana:v0.0.32-dev
Ingress:
  Enabled: true
Postgres:
  Pvc: false
