spring:
  application:
    name: lokahi-events

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog.xml

  kafka:
    bootstrap-servers: localhost:59092
    consumer:
      group-id: "event-service"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer

grpc:
  server:
    port: 6565
    deadline: 60000
  url:
    inventory: localhost:29065


kafka:
  raw-traps-topic: "traps"
  trap-events-topic: "events"
  internal-events-topic: "internal-event"

keycloak:
  realm: opennms
  base-url: http://onms-keycloak:8080/auth

management:
  endpoints:
    web:
      exposure:
        include: "*"
