{{ if not .Values.OpenShift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opennms-minion-grpc-route
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.MinionHost }}
  port:
    targetPort: {{ .Values.OpenNMS.MinionGateway.GrpcPort }}
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  to:
    kind: Service
    name: {{ .Values.OpenNMS.MinionGateway.ServiceName }}
{{ end }}