{{ if .Values.OpenShift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: opennms-ui-route
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Values.Host }}
  path: {{ .Values.OpenNMS.UI.Path }}  
  to:
    kind: Service
    name: {{ .Values.OpenNMS.UI.ServiceName }}
{{ end }}