apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
  labels:
    app: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.OpenNMS.MetricsProcessor.Replicas }}
  selector:
    matchLabels:
      run: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
  template:
    metadata:
      labels:
        appdomain: opennms
        run: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      containers:
        - name: {{ .Values.OpenNMS.MetricsProcessor.ServiceName }}
          image: {{ .Values.OpenNMS.MetricsProcessor.Image }}
          imagePullPolicy: {{ .Values.OpenNMS.MetricsProcessor.ImagePullPolicy }}
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y"  # FIXME: Permanent debug port, enable only for dev mode
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.Kafka.ServiceName }}:{{ .Values.Kafka.Port }}"
            - name: CORTEX_WRITE_URL
              value: {{ .Values.Cortex.Protocol }}://{{ .Values.Cortex.Host }}:{{ .Values.Cortex.Port }}{{ .Values.Cortex.PathWrite }}
          ports:
            - name: http
              containerPort: 8080
      {{- if .Values.OpenNMS.MetricsProcessor.PrivateRepoEnabled }}
      imagePullSecrets:
        - name: image-credentials
      {{- end }}
