apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ .Values.Keycloak.ServiceName }}-ri
  labels:
    app: keycloak-ri
  namespace: {{ .Values.Namespace }}
spec:
  keycloakCRName: {{ .Values.Keycloak.ServiceName }}
  realm:
    accessTokenLifespan: 6000
    id: {{ .Values.Keycloak.UUID.RealmId }}
    realm: {{ .Values.Keycloak.RealmName }}
    enabled: true
    loginTheme: "horizon-stream"
    emailTheme: "horizon-stream"
    rememberMe: true
    resetPasswordAllowed: true
    attributes:
      frontendUrl: "https://{{ .Values.Host }}{{ .Values.Keycloak.Path }}"
    clients:
      - id: {{ .Values.Keycloak.UUID.ClientId }}
        clientId: horizon-stream
        standardFlowEnabled: true
        enabled: true
        webOrigins:
          - "*"
        redirectUris:
          - "*"
        publicClient: true
        directAccessGrantsEnabled: true
        defaultClientScopes:
          - "web-origins"
          - "roles"
          - "profile"
          - "email"
        optionalClientScopes:
          - "address"
          - "phone"
          - "offline_access"
          - "microprofile-jwt"
    roles:
      realm:
      - id: {{ .Values.Keycloak.UUID.AdminUserId }}
        name: admin
        composite: false
      - id: {{ .Values.Keycloak.UUID.BaseUserId }}
        name: user
        composite: false
    users:
      - id: {{ .Values.Keycloak.UUID.AdminUserId }}
        username: {{ .Values.Keycloak.AdminUsername }}
        email: "admin@test.opennms.org"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "{{ .Values.Keycloak.AdminPassword }}"
        realmRoles:
          - "admin"
        clientRoles:
          account:
            - "manage-account"
            - "view-profile"
          realm-management:
            - "manage-users"
            - "view-users"
            - "query-users"
            - "create-client"
      - id: {{ .Values.Keycloak.UUID.BaseUserId }}
        username: {{ .Values.Keycloak.UserUsername }}
        firstName: "User001"
        lastName: ""
        email: "user001@test.opennms.org"
        enabled: True
        emailVerified: False
        credentials:
          - type: "password"
            value: "{{ .Values.Keycloak.UserPassword }}"
        realmRoles:
          - "user"
        clientRoles:
          account:
            - "manage-account"
            - "view-profile"
