apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: {{ .Values.Keycloak.ServiceName }}
  namespace: {{ .Values.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: {{ .Values.Keycloak.Port }}
    protocol: TCP
    targetPort: {{ .Values.Keycloak.Port }}
  selector:
    app: keycloak
  sessionAffinity: None
  type: ClusterIP