apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.MailServer.ServiceName }}
  labels:
    app: {{ .Values.MailServer.ServiceName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.MailServer.ServiceName }}
  replicas: {{ .Values.MailServer.Replicas }}
  template:
    metadata:
      labels:
        appdomain: opennms
        app: {{ .Values.MailServer.ServiceName }}
      annotations:
        kubectl.kubernetes.io/default-container: "{{ .Values.MailServer.ServiceName }}"
    spec:
      {{- if .Values.NodeRestrictions.Enabled }}
      nodeSelector:                                                                                    
        {{ .Values.NodeRestrictions.Key }}: {{ .Values.NodeRestrictions.Value }}                       
      tolerations:
        - effect: "NoSchedule"                                                                         
          key: "{{ .Values.NodeRestrictions.Key }}"                                                    
          operator: "Equal"
          value: {{ .Values.NodeRestrictions.Value }} 
      affinity: 
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:                                             
          - weight: 1                                                                                  
            preference:                                                                                
              matchExpressions:                                                                        
              - key: "{{ .Values.NodeRestrictions.Key }}"                                              
                operator: In
                values:                                                                                
                - {{ .Values.NodeRestrictions.Value }}                                                 
      {{- end }}
      containers:
        - name: {{ .Values.MailServer.ServiceName }}
          imagePullPolicy: {{ .Values.MailServer.ImagePullPolicy }}
          image: {{ .Values.MailServer.Image }}
          ports:
            - name: http
              containerPort: {{ .Values.MailServer.Port }}
            - name: smtp
              containerPort: {{ .Values.MailServer.SmtpPort }}
          resources:
            limits:
              cpu: "{{ .Values.MailServer.Resources.Limits.Cpu }}"
              memory: "{{ .Values.MailServer.Resources.Limits.Memory }}"
            requests:
              cpu: "{{ .Values.MailServer.Resources.Requests.Cpu }}"
              memory: "{{ .Values.MailServer.Resources.Requests.Memory }}"
