spring:
  application:
    name: horizon-stream-notifications

  mail:
    from: noreply@opennms.com
    host: mail-server
    port: 1025

  datasource:
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      group-id: org.opennms.horizon.notifications
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

  liquibase:
    change-log: db/changelog/changelog.xml

  jpa:
    hibernate:
      ddl-auto: validate

grpc:
  server:
    port: 6565

horizon:
  kafka:
    alerts:
      topic: alerts
      concurrency: 1
    monitoring-policy:
      topic: monitoring-policy
      concurrency: 1

  pagerduty:
    client: OpenNMS
    clientURL: http://opennms.com

  keycloak:
    realm: opennms
    use-static-pubkey: false
    keycloakRequireSsl: false
    static-pubkey-path: etc/keycloak-pubkey.pem
    admin-realm: master
    base-url: http://onms-keycloak:8080/auth
    admin-username: admin
    admin-password: admin
    client-id: admin-cli
